### ISSUE TITLE
compile failed, ERROR: OTP release 20 does not match required regex R16|17|18|19

### ISSUE THREAD

**Issue by liu-chong** [emqtt/emq-relx#77]
./rebar compile
==> getopt (compile)
ERROR: OTP release 20 does not match required regex R16|17|18|19
ERROR: compile failed while processing /home/liuchong/work/emqttd/deps/getopt: rebar_abort

**Comment by m-menon** [comment]
Is there an update on this? Thanks

**Comment by turtleDeng** [comment]
@m-menon 
This issue has been fixed in https://github.com/emqtt/cuttlefish/commit/99d276540f4f097c16eac4a97edff0bdbe2f1397
```
rm -rf deps/cuttlefish

make
```

**Comment by aranip** [comment]
Hi all, I am trying to install Riak on my mac os, but whenever I try to do "make devrel" command,  i tried the fix mentioned but still getting the below errors.

"erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information."

**Comment by emqplus** [comment]
@aranip The EMQ 2.3 will be compatible with Erlang/OTP R20

**Comment by joshzinny** [comment]
Hi guy, I am having this same problem. Is there any solution to this? Thanks in advance
joshzinny:riak joshzinny$ make devrel
./rebar get-deps
WARN: Missing plugins: [rebar_lock_deps_plugin]
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (get-deps)
==> riak_pb (get-deps)
WARN: Missing plugins: [rebar_lock_deps_plugin]
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> mochiweb (get-deps)
==> webmachine (get-deps)
==> riak_api (get-deps)
WARN: Missing plugins: [rebar_lock_deps_plugin]
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> proper (get-deps)
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> stdlib2 (get-deps)
==> hyper (get-deps)
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> chronos (get-deps)
==> riak_kv (get-deps)
WARN: Missing plugins: [rebar_lock_deps_plugin]
WARN: Missing plugins: [rebar_lock_deps_plugin]
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> rel (get-deps)
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> riak (get-deps)
==> riak (get-deps)
./rebar compile
WARN: Missing plugins: [rebar_lock_deps_plugin]
WARN: Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (compile)
ERROR: OTP release 21 does not match required regex R16|17
ERROR: compile failed while processing /Users/joshzinny/riak/deps/rebar_lock_deps_plugin: rebar_abort
make: *** [compile] Error 1

**Comment by Gilbert-Wong** [comment]
Are you sure the broker you use is em
